#!/usr/bin/env python3
# Copyright (c) 2025 GenOrca. All Rights Reserved.

"""
Validates that the dispatcher action catalog and Action Registry v2 are in
sync with the plugin's ue_* function signatures and literal metadata.

Both dispatchers/_catalog.py and dispatchers/_registry.py are generated by
generate_catalog.py. This script re-runs the generator in --check mode and
fails when either committed view differs from its source declarations.

This catches the bug class where catalog param names drift from the real
ue_* signatures (the dispatcher passes params straight through as
ue_func(**params), so a name mismatch = runtime failure).

Usage:
    python validate_tools.py
"""

import subprocess
import sys
from pathlib import Path

GENERATOR = Path(__file__).parent / "generate_catalog.py"


def main():
    result = subprocess.run(
        [sys.executable, str(GENERATOR), "--check"],
        capture_output=True,
        text=True,
    )
    sys.stdout.write(result.stdout)
    sys.stderr.write(result.stderr)
    if result.returncode:
        sys.exit(result.returncode)

    from unreal_mcp.dispatcher import _LOCAL_ACTIONS
    from unreal_mcp.special_action_specs import SPECIAL_ACTION_SPECS

    special = {
        domain: set(actions) for domain, actions in SPECIAL_ACTION_SPECS.items()
    }
    local = {domain: set(actions) for domain, actions in _LOCAL_ACTIONS.items()}
    if special != local:
        print(
            "FAIL: SPECIAL_ACTION_SPECS and dispatcher local branches differ: "
            f"special={special}, local={local}"
        )
        sys.exit(1)


if __name__ == "__main__":
    main()
